/******************************************************************************************
1) Top 10 Categories by Revenue
   - Computes total revenue generated by each product category.
   - Uses SUM(Amount) and returns the top 10 revenue-generating categories.
******************************************************************************************/

SELECT 
  Category,
  FLOOR(SUM(Amount)) AS total_revenue
FROM "Amazon"
GROUP BY Category
ORDER BY total_revenue DESC
LIMIT 10;



/******************************************************************************************
Monthly fulfillment performance
- For each month, shows total orders, total units, delivered count, cancelled count,
  delivery rate and cancellation rate.
******************************************************************************************/
SELECT
  SUBSTRING("Date", 1, 7) AS month,
  COUNT(DISTINCT "Order ID") AS total_orders,
  SUM(REPLACE("Qty", '"', '')::numeric) AS total_units,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%deliver%') AS delivered,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%') AS cancelled,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%deliver%')
    / NULLIF(COUNT(DISTINCT "Order ID"), 0), 2
  ) AS delivery_rate_pct,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%')
    / NULLIF(COUNT(DISTINCT "Order ID"), 0), 2
  ) AS cancel_rate_pct
FROM "Amazon"
WHERE "Date" IS NOT NULL
GROUP BY month
ORDER BY month ASC;



/******************************************************************************************
3) Order Status Distribution (% Share)
   - Shows how many distinct orders fall into each order status.
   - Computes what % each status contributes to total orders.
******************************************************************************************/

SELECT 
  Status,
  COUNT(DISTINCT "Order ID") AS orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") / 
    (SELECT COUNT(DISTINCT "Order ID") FROM "Amazon"),
    2
  ) AS pct_share
FROM "Amazon"
GROUP BY Status
ORDER BY orders DESC;



/******************************************************************************************
4) State-wise Order Share (%)
   - Calculates order count by state.
   - Computes % contribution of each state relative to the top 10.
******************************************************************************************/

SELECT
  state,
  orders,
  ROUND(100.0 * orders / SUM(orders) OVER (), 2) AS state_share_pct
FROM (
  SELECT
    "ship-state" AS state,
    COUNT(DISTINCT "Order ID") AS orders
  FROM "Amazon"
  WHERE "ship-state" IS NOT NULL
  GROUP BY "ship-state"
  ORDER BY orders DESC
  LIMIT 10
) AS t
ORDER BY orders DESC;



/******************************************************************************************
5) Busiest Order Date + Order Count
   - Identifies the dates with the highest number of distinct orders.
   - Shows the top 10 busiest days.
******************************************************************************************/

SELECT
  "Date",
  COUNT(DISTINCT "Order ID") AS orders
FROM "Amazon"
WHERE "Date" IS NOT NULL
GROUP BY "Date"
ORDER BY orders DESC
LIMIT 10;



/******************************************************************************************
6) Month-wise Order Throughput & Units Summary
   - Shows total distinct orders and total units sold each month.
   - Highlights throughput (orders) and item movement (units).
******************************************************************************************/

SELECT
  SUBSTRING("Date", 1, 7) AS month,
  COUNT(DISTINCT "Order ID") AS total_orders,
  SUM("Qty") AS total_units
FROM "Amazon"
GROUP BY month
ORDER BY month ASC;



/******************************************************************************************
7) Fulfillment Method Breakdown (Amazon vs Merchant)
   - Counts the quantity fulfilled by each fulfillment method.
******************************************************************************************/

SELECT 
  Fulfilment,
  COUNT("Qty") AS Qty
FROM "Amazon"
GROUP BY Fulfilment
ORDER BY Qty DESC;



/******************************************************************************************
8) Courier Status & Order Counts
   - Shows shipped, unshipped, cancelled order counts.
******************************************************************************************/

SELECT 
  "courier status",
  COUNT(DISTINCT "order id") AS orders
FROM "Amazon"
WHERE "courier status" IS NOT NULL
GROUP BY "courier status"
ORDER BY orders DESC
LIMIT 10;



/******************************************************************************************
9) Month-wise Total Purchases by City
   - For each month, shows which cities placed the most distinct orders.
******************************************************************************************/

SELECT
  SUBSTRING("Date", 1, 7) AS month,
  "ship-city",
  COUNT(DISTINCT "Order ID") AS total_orders
FROM "Amazon"
WHERE "Date" IS NOT NULL
GROUP BY month, "ship-city"
ORDER BY month ASC, total_orders DESC;


/******************************************************************************************
Cancellation Hotspots — by Category
What it does:
  - For each Category, reports total orders, cancelled orders and cancellation rate (pct).
  - Use this to surface categories with unusually high cancellation rates.
Notes:
  - Adjust HAVING threshold (>50) if you want to include smaller categories.
******************************************************************************************/
SELECT
  Category,
  COUNT(DISTINCT "Order ID") AS total_orders,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%') AS cancelled_orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%')
    / NULLIF(COUNT(DISTINCT "Order ID"), 0),
  2) AS cancel_rate_pct
FROM "Amazon"
WHERE Category IS NOT NULL
GROUP BY Category
HAVING COUNT(DISTINCT "Order ID") > 50
ORDER BY cancel_rate_pct DESC
LIMIT 50;


/******************************************************************************************
Cancellation Hotspots — by State
What it does:
  - For each ship-state, reports total orders, cancelled orders and cancellation rate (pct).
  - Good for detecting regional operational problems.
Notes:
  - Adjust HAVING threshold (>200) to filter out low-volume states.
******************************************************************************************/
SELECT
  "ship-state" AS state,
  COUNT(DISTINCT "Order ID") AS total_orders,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%') AS cancelled_orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%')
    / NULLIF(COUNT(DISTINCT "Order ID"), 0),
  2) AS cancel_rate_pct
FROM "Amazon"
WHERE "ship-state" IS NOT NULL
GROUP BY "ship-state"
HAVING COUNT(DISTINCT "Order ID") > 200
ORDER BY cancel_rate_pct DESC
LIMIT 50;


/******************************************************************************************
Return Rate — Category-wise
What it does:
  - For each Category, reports total orders, return-related orders and return rate (pct).
  - Detect categories with high return behavior (quality / listing issues).
Notes:
  - This checks Status strings for common return/refund keywords; tweak patterns if needed.
******************************************************************************************/
SELECT
  Category,
  COUNT(DISTINCT "Order ID") AS total_orders,
  COUNT(DISTINCT "Order ID") FILTER (
    WHERE Status ILIKE '%return%' OR Status ILIKE '%refund%' OR Status ILIKE '%returned%'
  ) AS return_orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (
      WHERE Status ILIKE '%return%' OR Status ILIKE '%refund%' OR Status ILIKE '%returned%'
    ) / NULLIF(COUNT(DISTINCT "Order ID"), 0),
  2) AS return_rate_pct
FROM "Amazon"
WHERE Category IS NOT NULL
GROUP BY Category
HAVING COUNT(DISTINCT "Order ID") > 50
ORDER BY return_rate_pct DESC
LIMIT 50;

/******************************************************************************************
SKUs with highest defect rates (cancellations)
- Lists SKUs with high cancellation rates (defect candidates) and revenue at risk.
- Filters out very low-volume SKUs to avoid noise.
******************************************************************************************/
SELECT
  SKU,
  Category,
  COUNT(DISTINCT "Order ID") AS orders,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%') AS cancelled,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%')
    / NULLIF(COUNT(DISTINCT "Order ID"), 0), 2
  ) AS defect_rate_pct,
  SUM("Amount"::numeric) AS revenue_at_risk
FROM "Amazon"
WHERE SKU IS NOT NULL
GROUP BY SKU, Category
HAVING COUNT(DISTINCT "Order ID") > 10
ORDER BY defect_rate_pct DESC, orders DESC
LIMIT 20;

/******************************************************************************************
Courier / dispatch status performance
- For each "courier status" bucket, reports order count, percent of total orders,
  cancelled orders for that bucket, and the cancel_rate within the bucket.
******************************************************************************************/
SELECT
  "courier status",
  COUNT(DISTINCT "Order ID") AS orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") / NULLIF((SELECT COUNT(DISTINCT "Order ID") FROM "Amazon"),0),
    2
  ) AS pct_of_total_orders,
  COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%') AS cancelled_orders,
  ROUND(
    100.0 * COUNT(DISTINCT "Order ID") FILTER (WHERE Status ILIKE '%cancel%')
    / NULLIF(COUNT(DISTINCT "Order ID"),0), 2
  ) AS cancel_rate_pct_for_courier_status
FROM "Amazon"
WHERE "courier status" IS NOT NULL
GROUP BY "courier status"
ORDER BY orders DESC;


